### ISSUE TITLE
Throws an error on IE11

### ISSUE THREAD

**Issue by klaygomes** [inspect-js/functions-have-names#11]
On IE11 it is throwing the following error:  

You see the problem is getOwnPropertyDescriptor returns `undefined`.

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/522884/163960382-5e996f85-c076-42fc-8b98-e0f3d04b2be0.png">

**Comment by yiyawu** [comment]
The same thing happened to me

**Comment by Sayahmet** [comment]
same problem today :(

**Comment by klaygomes** [comment]
If you are having this problem, probably it is because of `regexp.prototype.flags` which started using this as dependency. While it is not fixed, you can work around it by including the following line in your `package.json`.

```json
  "resolutions": {
    "regexp.prototype.flags": "1.4.2"
  },
```

**Comment by ljharb** [comment]
That’s for yarn; npm uses “overrides”.

I’ll have a fix out for this in the next few hours.

**Comment by ljharb** [comment]
Also note: another solution in the meantime is to use https://npmjs.com/function.prototype.name, which polyfills function names in IE 9-11 :-)
